
#ifndef CVAST_VAST4_NODETYPES_HPP
#define CVAST_VAST4_NODETYPES_HPP

namespace Cvast {
    namespace Vast4 {
        struct V4T {
            enum nodeTypes {
                VAST = 1,
                ERROR = 2,
                AD = 3,
                INLINE = 4,
                ADSYSTEM = 5,
                ADTITLE = 6,
                IMPRESSION = 7,
                CATEGORY = 8,
                DESCRIPTION = 9,
                ADVERTISER = 10,
                PRICING = 11,
                SURVEY = 12,
                VIEWABLEIMPRESSION = 13,
                VIEWABLE = 14,
                NOTVIEWABLE = 15,
                VIEWUNDETERMINED = 16,
                CREATIVES = 17,
                CREATIVE = 18,
                UNIVERSALADID = 19,
                CREATIVEEXTENSIONS = 20,
                CREATIVEEXTENSION = 21,
                LINEAR = 22,
                DURATION = 23,
                ADPARAMETERS = 24,
                MEDIAFILES = 25,
                MEDIAFILE = 26,
                MEZZANINE = 27,
                INTERACTIVECREATIVEFILE = 28,
                VIDEOCLICKS = 29,
                CLICKTHROUGH = 30,
                CLICKTRACKING = 31,
                CUSTOMCLICK = 32,
                ICONS = 33,
                ICON = 34,
                ICONVIEWTRACKING = 35,
                ICONCLICKS = 36,
                ICONCLICKTHROUGH = 37,
                ICONCLICKTRACKING = 38,
                NONLINEARADS = 39,
                NONLINEAR = 40,
                NONLINEARCLICKTHROUGH = 41,
                NONLINEARCLICKTRACKING = 42,
                COMPANIONADS = 43,
                COMPANION = 44,
                ALTTEXT = 45,
                COMPANIONCLICKTHROUGH = 46,
                COMPANIONCLICKTRACKING = 47,
                TRACKINGEVENTS = 48,
                TRACKING = 49,
                STATICRESOURCE = 50,
                IFRAMERESOURCE = 51,
                HTMLRESOURCE = 52,
                ADVERIFICATIONS = 53,
                VERIFICATION = 54,
                JAVASCRIPTRESOURCE = 55,
                FLASHRESOURCE = 56,
                EXTENSIONS = 57,
                EXTENSION = 58,
                WRAPPER = 59,
                VASTADTAGURI = 60
            };
            std::map<std::string, int> nodeTags;

            V4T () {
                nodeTags = {
                        {"VAST", VAST},
                        {"ERROR", ERROR},
                        {"AD", AD},
                        {"INLINE", INLINE},
                        {"ADSYSTEM", ADSYSTEM},
                        {"ADTITLE", ADTITLE},
                        {"IMPRESSION", IMPRESSION},
                        {"CATEGORY", CATEGORY},
                        {"DESCRIPTION", DESCRIPTION},
                        {"ADVERTISER", ADVERTISER},
                        {"PRICING", PRICING},
                        {"SURVEY", SURVEY},
                        {"VIEWABLEIMPRESSION", VIEWABLEIMPRESSION},
                        {"VIEWABLE", VIEWABLE},
                        {"NOTVIEWABLE", NOTVIEWABLE},
                        {"VIEWUNDETERMINED", VIEWUNDETERMINED},
                        {"CREATIVES", CREATIVES},
                        {"CREATIVE", CREATIVE},
                        {"UNIVERSALADID", UNIVERSALADID},
                        {"CREATIVEEXTENSIONS", CREATIVEEXTENSIONS},
                        {"CREATIVEEXTENSION", CREATIVEEXTENSION},
                        {"LINEAR", LINEAR},
                        {"DURATION", DURATION},
                        {"ADPARAMETERS", ADPARAMETERS},
                        {"MEDIAFILES", MEDIAFILES},
                        {"MEDIAFILE", MEDIAFILE},
                        {"MEZZANINE", MEZZANINE},
                        {"INTERACTIVECREATIVEFILE", INTERACTIVECREATIVEFILE},
                        {"VIDEOCLICKS", VIDEOCLICKS},
                        {"CLICKTHROUGH", CLICKTHROUGH},
                        {"CLICKTRACKING", CLICKTRACKING},
                        {"CUSTOMCLICK", CUSTOMCLICK},
                        {"ICONS", ICONS},
                        {"ICON", ICON},
                        {"ICONVIEWTRACKING", ICONVIEWTRACKING},
                        {"ICONCLICKS", ICONCLICKS},
                        {"ICONCLICKTHROUGH", ICONCLICKTHROUGH},
                        {"ICONCLICKTRACKING", ICONCLICKTRACKING},
                        {"NONLINEARADS", NONLINEARADS},
                        {"NONLINEAR", NONLINEAR},
                        {"NONLINEARCLICKTHROUGH", NONLINEARCLICKTHROUGH},
                        {"NONLINEARCLICKTRACKING", NONLINEARCLICKTRACKING},
                        {"COMPANIONADS", COMPANIONADS},
                        {"COMPANION", COMPANION},
                        {"ALTTEXT", ALTTEXT},
                        {"COMPANIONCLICKTHROUGH", COMPANIONCLICKTHROUGH},
                        {"COMPANIONCLICKTRACKING", COMPANIONCLICKTRACKING},
                        {"TRACKINGEVENTS", TRACKINGEVENTS},
                        {"TRACKING", TRACKING},
                        {"STATICRESOURCE", STATICRESOURCE},
                        {"IFRAMERESOURCE", IFRAMERESOURCE},
                        {"HTMLRESOURCE", HTMLRESOURCE},
                        {"ADVERIFICATIONS", ADVERIFICATIONS},
                        {"VERIFICATION", VERIFICATION},
                        {"JAVASCRIPTRESOURCE", JAVASCRIPTRESOURCE},
                        {"FLASHRESOURCE", FLASHRESOURCE},
                        {"EXTENSIONS", EXTENSIONS},
                        {"EXTENSION", EXTENSION},
                        {"WRAPPER", WRAPPER},
                        {"VASTADTAGURI", VASTADTAGURI}
                };
            }
        };
    }
}

#endif